// ============================================================
// IronLog — Complete Exercise Database
// ============================================================
import type { ExerciseInfo } from '@/types'

export const exerciseDatabase: ExerciseInfo[] = [
    // ==================== CHEST ====================
    { name: 'Flat Barbell Bench Press', bodyPart: 'Chest', category: 'compound' },
    { name: 'Incline Barbell Bench Press', bodyPart: 'Chest', category: 'compound' },
    { name: 'Decline Barbell Bench Press', bodyPart: 'Chest', category: 'compound' },
    { name: 'Flat Dumbbell Press', bodyPart: 'Chest', category: 'compound' },
    { name: 'Incline Dumbbell Press', bodyPart: 'Chest', category: 'compound' },
    { name: 'Decline Dumbbell Press', bodyPart: 'Chest', category: 'compound' },
    { name: 'Flat Dumbbell Flyes', bodyPart: 'Chest', category: 'isolation' },
    { name: 'Incline Dumbbell Flyes', bodyPart: 'Chest', category: 'isolation' },
    { name: 'Decline Dumbbell Flyes', bodyPart: 'Chest', category: 'isolation' },
    { name: 'High Cable Flyes', bodyPart: 'Chest', category: 'isolation' },
    { name: 'Mid Cable Flyes', bodyPart: 'Chest', category: 'isolation' },
    { name: 'Low Cable Flyes', bodyPart: 'Chest', category: 'isolation' },
    { name: 'Machine Chest Press', bodyPart: 'Chest', category: 'compound' },
    { name: 'Machine Chest Fly (Pec Deck)', bodyPart: 'Chest', category: 'isolation' },
    { name: 'Standard Push-Ups', bodyPart: 'Chest', category: 'bodyweight' },
    { name: 'Wide Push-Ups', bodyPart: 'Chest', category: 'bodyweight' },
    { name: 'Diamond Push-Ups', bodyPart: 'Chest', category: 'bodyweight' },
    { name: 'Decline Push-Ups', bodyPart: 'Chest', category: 'bodyweight' },
    { name: 'Incline Push-Ups', bodyPart: 'Chest', category: 'bodyweight' },
    { name: 'Chest Dips', bodyPart: 'Chest', category: 'compound' },
    { name: 'Landmine Press', bodyPart: 'Chest', category: 'compound' },
    { name: 'Svend Press', bodyPart: 'Chest', category: 'isolation' },
    { name: 'Smith Machine Flat Bench Press', bodyPart: 'Chest', category: 'compound' },
    { name: 'Smith Machine Incline Bench Press', bodyPart: 'Chest', category: 'compound' },
    { name: 'Smith Machine Decline Bench Press', bodyPart: 'Chest', category: 'compound' },

    // ==================== BACK ====================
    { name: 'Barbell Bent Over Row', bodyPart: 'Back', category: 'compound' },
    { name: 'Pendlay Row', bodyPart: 'Back', category: 'compound' },
    { name: 'T-Bar Row', bodyPart: 'Back', category: 'compound' },
    { name: 'Single Arm Dumbbell Row', bodyPart: 'Back', category: 'compound' },
    { name: 'Dumbbell Pullover', bodyPart: 'Back', category: 'isolation' },
    { name: 'Wide Grip Pull-Ups', bodyPart: 'Back', category: 'bodyweight' },
    { name: 'Close Grip Pull-Ups', bodyPart: 'Back', category: 'bodyweight' },
    { name: 'Neutral Grip Pull-Ups', bodyPart: 'Back', category: 'bodyweight' },
    { name: 'Chin-Ups', bodyPart: 'Back', category: 'bodyweight' },
    { name: 'Wide Grip Lat Pulldown', bodyPart: 'Back', category: 'compound' },
    { name: 'Close Grip Lat Pulldown', bodyPart: 'Back', category: 'compound' },
    { name: 'Reverse Grip Lat Pulldown', bodyPart: 'Back', category: 'compound' },
    { name: 'Single Arm Lat Pulldown', bodyPart: 'Back', category: 'compound' },
    { name: 'Wide Grip Seated Cable Row', bodyPart: 'Back', category: 'compound' },
    { name: 'Close Grip Seated Cable Row', bodyPart: 'Back', category: 'compound' },
    { name: 'Single Arm Seated Cable Row', bodyPart: 'Back', category: 'compound' },
    { name: 'Face Pulls', bodyPart: 'Back', category: 'isolation' },
    { name: 'Straight Arm Pulldown', bodyPart: 'Back', category: 'isolation' },
    { name: 'Chest Supported Machine Row', bodyPart: 'Back', category: 'compound' },
    { name: 'Machine Pullover', bodyPart: 'Back', category: 'isolation' },
    { name: 'Barbell Shrugs', bodyPart: 'Back', category: 'isolation' },
    { name: 'Dumbbell Shrugs', bodyPart: 'Back', category: 'isolation' },
    { name: 'Hyperextensions', bodyPart: 'Back', category: 'isolation' },
    { name: 'Rack Pulls', bodyPart: 'Back', category: 'compound' },
    { name: 'Meadows Row', bodyPart: 'Back', category: 'compound' },
    { name: 'Kroc Row', bodyPart: 'Back', category: 'compound' },
    { name: 'Helms Row', bodyPart: 'Back', category: 'compound' },
    { name: 'Smith Machine Row', bodyPart: 'Back', category: 'compound' },
    { name: 'Cable Pullover', bodyPart: 'Back', category: 'isolation' },
    { name: 'Inverted Row', bodyPart: 'Back', category: 'bodyweight' },
    { name: 'Seal Row', bodyPart: 'Back', category: 'compound' },

    // ==================== SHOULDERS ====================
    { name: 'Standing Barbell Overhead Press', bodyPart: 'Shoulders', category: 'compound' },
    { name: 'Seated Barbell Overhead Press', bodyPart: 'Shoulders', category: 'compound' },
    { name: 'Seated Dumbbell Shoulder Press', bodyPart: 'Shoulders', category: 'compound' },
    { name: 'Standing Dumbbell Shoulder Press', bodyPart: 'Shoulders', category: 'compound' },
    { name: 'Arnold Press', bodyPart: 'Shoulders', category: 'compound' },
    { name: 'Dumbbell Lateral Raises', bodyPart: 'Shoulders', category: 'isolation' },
    { name: 'Cable Lateral Raises', bodyPart: 'Shoulders', category: 'isolation' },
    { name: 'Machine Lateral Raises', bodyPart: 'Shoulders', category: 'isolation' },
    { name: 'Dumbbell Front Raises', bodyPart: 'Shoulders', category: 'isolation' },
    { name: 'Barbell Front Raises', bodyPart: 'Shoulders', category: 'isolation' },
    { name: 'Cable Front Raises', bodyPart: 'Shoulders', category: 'isolation' },
    { name: 'Plate Front Raises', bodyPart: 'Shoulders', category: 'isolation' },
    { name: 'Dumbbell Rear Delt Flyes', bodyPart: 'Shoulders', category: 'isolation' },
    { name: 'Cable Rear Delt Flyes', bodyPart: 'Shoulders', category: 'isolation' },
    { name: 'Reverse Pec Deck', bodyPart: 'Shoulders', category: 'isolation' },
    { name: 'Barbell Upright Row', bodyPart: 'Shoulders', category: 'compound' },
    { name: 'Dumbbell Upright Row', bodyPart: 'Shoulders', category: 'compound' },
    { name: 'Cable Upright Row', bodyPart: 'Shoulders', category: 'compound' },
    { name: 'Cable Face Pulls', bodyPart: 'Shoulders', category: 'isolation' },
    { name: 'Machine Shoulder Press', bodyPart: 'Shoulders', category: 'compound' },
    { name: 'Landmine Shoulder Press', bodyPart: 'Shoulders', category: 'compound' },
    { name: 'Z-Press', bodyPart: 'Shoulders', category: 'compound' },
    { name: 'Viking Press', bodyPart: 'Shoulders', category: 'compound' },
    { name: 'Bradford Press', bodyPart: 'Shoulders', category: 'compound' },
    { name: 'Bus Drivers', bodyPart: 'Shoulders', category: 'isolation' },
    { name: 'Behind the Neck Press', bodyPart: 'Shoulders', category: 'compound' },
    { name: 'Lu Raises', bodyPart: 'Shoulders', category: 'isolation' },
    { name: 'Plate Raises', bodyPart: 'Shoulders', category: 'isolation' },
    { name: 'Handstand Push-Ups', bodyPart: 'Shoulders', category: 'bodyweight' },

    // ==================== BICEPS ====================
    { name: 'Straight Bar Barbell Curl', bodyPart: 'Biceps', category: 'isolation' },
    { name: 'EZ Bar Curl', bodyPart: 'Biceps', category: 'isolation' },
    { name: 'Standing Dumbbell Curl', bodyPart: 'Biceps', category: 'isolation' },
    { name: 'Seated Dumbbell Curl', bodyPart: 'Biceps', category: 'isolation' },
    { name: 'Alternating Dumbbell Curl', bodyPart: 'Biceps', category: 'isolation' },
    { name: 'Dumbbell Hammer Curl', bodyPart: 'Biceps', category: 'isolation' },
    { name: 'Rope Cable Hammer Curl', bodyPart: 'Biceps', category: 'isolation' },
    { name: 'Barbell Preacher Curl', bodyPart: 'Biceps', category: 'isolation' },
    { name: 'Dumbbell Preacher Curl', bodyPart: 'Biceps', category: 'isolation' },
    { name: 'Machine Preacher Curl', bodyPart: 'Biceps', category: 'isolation' },
    { name: 'EZ Bar Preacher Curl', bodyPart: 'Biceps', category: 'isolation' },
    { name: 'Concentration Curl', bodyPart: 'Biceps', category: 'isolation' },
    { name: 'Incline Dumbbell Curl', bodyPart: 'Biceps', category: 'isolation' },
    { name: 'Straight Bar Cable Curl', bodyPart: 'Biceps', category: 'isolation' },
    { name: 'Rope Cable Curl', bodyPart: 'Biceps', category: 'isolation' },
    { name: 'Single Arm Cable Curl', bodyPart: 'Biceps', category: 'isolation' },
    { name: 'Spider Curl', bodyPart: 'Biceps', category: 'isolation' },
    { name: 'Drag Curl', bodyPart: 'Biceps', category: 'isolation' },
    { name: 'Barbell Reverse Curl', bodyPart: 'Biceps', category: 'isolation' },
    { name: 'Dumbbell Reverse Curl', bodyPart: 'Biceps', category: 'isolation' },
    { name: 'EZ Bar Reverse Curl', bodyPart: 'Biceps', category: 'isolation' },
    { name: '21s', bodyPart: 'Biceps', category: 'isolation' },
    { name: 'Zottman Curl', bodyPart: 'Biceps', category: 'isolation' },
    { name: 'Machine Bicep Curl', bodyPart: 'Biceps', category: 'isolation' },
    { name: 'Cross Body Hammer Curl', bodyPart: 'Biceps', category: 'isolation' },

    // ==================== TRICEPS ====================
    { name: 'Close Grip Bench Press', bodyPart: 'Triceps', category: 'compound' },
    { name: 'Barbell Skull Crushers', bodyPart: 'Triceps', category: 'isolation' },
    { name: 'EZ Bar Skull Crushers', bodyPart: 'Triceps', category: 'isolation' },
    { name: 'Dumbbell Skull Crushers', bodyPart: 'Triceps', category: 'isolation' },
    { name: 'Rope Tricep Pushdown', bodyPart: 'Triceps', category: 'isolation' },
    { name: 'Straight Bar Tricep Pushdown', bodyPart: 'Triceps', category: 'isolation' },
    { name: 'V-Bar Tricep Pushdown', bodyPart: 'Triceps', category: 'isolation' },
    { name: 'Single Arm Tricep Pushdown', bodyPart: 'Triceps', category: 'isolation' },
    { name: 'Barbell Overhead Tricep Extension', bodyPart: 'Triceps', category: 'isolation' },
    { name: 'Dumbbell Overhead Tricep Extension', bodyPart: 'Triceps', category: 'isolation' },
    { name: 'Cable Overhead Tricep Extension', bodyPart: 'Triceps', category: 'isolation' },
    { name: 'EZ Bar Overhead Tricep Extension', bodyPart: 'Triceps', category: 'isolation' },
    { name: 'Dumbbell Kickbacks', bodyPart: 'Triceps', category: 'isolation' },
    { name: 'Tricep Dips', bodyPart: 'Triceps', category: 'compound' },
    { name: 'Diamond Push-Ups (Triceps)', bodyPart: 'Triceps', category: 'bodyweight' },
    { name: 'JM Press', bodyPart: 'Triceps', category: 'compound' },
    { name: 'Tate Press', bodyPart: 'Triceps', category: 'isolation' },
    { name: 'French Press', bodyPart: 'Triceps', category: 'isolation' },
    { name: 'Machine Overhead Tricep Extension', bodyPart: 'Triceps', category: 'isolation' },
    { name: 'Machine Tricep Pushdown', bodyPart: 'Triceps', category: 'isolation' },
    { name: 'Board Press', bodyPart: 'Triceps', category: 'compound' },

    // ==================== QUADS ====================
    { name: 'Barbell Back Squat', bodyPart: 'Quads', category: 'compound' },
    { name: 'Front Squat', bodyPart: 'Quads', category: 'compound' },
    { name: 'Goblet Squat', bodyPart: 'Quads', category: 'compound' },
    { name: 'Leg Press', bodyPart: 'Quads', category: 'compound' },
    { name: 'Single Leg Press', bodyPart: 'Quads', category: 'compound' },
    { name: 'Narrow Stance Leg Press', bodyPart: 'Quads', category: 'compound' },
    { name: 'Wide Stance Leg Press', bodyPart: 'Quads', category: 'compound' },
    { name: 'Machine Hack Squat', bodyPart: 'Quads', category: 'compound' },
    { name: 'Barbell Hack Squat', bodyPart: 'Quads', category: 'compound' },
    { name: 'Leg Extension', bodyPart: 'Quads', category: 'isolation' },
    { name: 'Single Leg Extension', bodyPart: 'Quads', category: 'isolation' },
    { name: 'Bulgarian Split Squat', bodyPart: 'Quads', category: 'compound' },
    { name: 'Walking Lunges', bodyPart: 'Quads', category: 'compound' },
    { name: 'Reverse Lunges', bodyPart: 'Quads', category: 'compound' },
    { name: 'Forward Lunges', bodyPart: 'Quads', category: 'compound' },
    { name: 'Step-Ups', bodyPart: 'Quads', category: 'compound' },
    { name: 'Box Squats', bodyPart: 'Quads', category: 'compound' },
    { name: 'Pause Squats', bodyPart: 'Quads', category: 'compound' },
    { name: 'Smith Machine Squat', bodyPart: 'Quads', category: 'compound' },
    { name: 'Pendulum Squat', bodyPart: 'Quads', category: 'compound' },
    { name: 'Sissy Squat', bodyPart: 'Quads', category: 'bodyweight' },
    { name: 'Wall Sit', bodyPart: 'Quads', category: 'bodyweight' },
    { name: 'Belt Squat', bodyPart: 'Quads', category: 'compound' },
    { name: 'Safety Bar Squat', bodyPart: 'Quads', category: 'compound' },
    { name: 'Pistol Squat', bodyPart: 'Quads', category: 'bodyweight' },
    { name: 'Cyclist Squat', bodyPart: 'Quads', category: 'compound' },

    // ==================== HAMSTRINGS ====================
    { name: 'Barbell Romanian Deadlift', bodyPart: 'Hamstrings', category: 'compound' },
    { name: 'Dumbbell Romanian Deadlift', bodyPart: 'Hamstrings', category: 'compound' },
    { name: 'Single Leg Romanian Deadlift', bodyPart: 'Hamstrings', category: 'compound' },
    { name: 'Conventional Deadlift', bodyPart: 'Hamstrings', category: 'compound' },
    { name: 'Sumo Deadlift', bodyPart: 'Hamstrings', category: 'compound' },
    { name: 'Stiff-Leg Deadlift', bodyPart: 'Hamstrings', category: 'compound' },
    { name: 'Lying Leg Curl', bodyPart: 'Hamstrings', category: 'isolation' },
    { name: 'Seated Leg Curl', bodyPart: 'Hamstrings', category: 'isolation' },
    { name: 'Standing Leg Curl', bodyPart: 'Hamstrings', category: 'isolation' },
    { name: 'Nordic Hamstring Curl', bodyPart: 'Hamstrings', category: 'bodyweight' },
    { name: 'Good Mornings', bodyPart: 'Hamstrings', category: 'compound' },
    { name: 'Glute Ham Raise', bodyPart: 'Hamstrings', category: 'compound' },
    { name: 'Cable Pull Through', bodyPart: 'Hamstrings', category: 'compound' },
    { name: 'Kettlebell Swing', bodyPart: 'Hamstrings', category: 'compound' },
    { name: 'Barbell Hip Thrust', bodyPart: 'Hamstrings', category: 'compound' },
    { name: 'Swiss Ball Leg Curl', bodyPart: 'Hamstrings', category: 'isolation' },

    // ==================== GLUTES ====================
    { name: 'Barbell Hip Thrust (Glutes)', bodyPart: 'Glutes', category: 'compound' },
    { name: 'Dumbbell Hip Thrust', bodyPart: 'Glutes', category: 'compound' },
    { name: 'Smith Machine Hip Thrust', bodyPart: 'Glutes', category: 'compound' },
    { name: 'Cable Kickback', bodyPart: 'Glutes', category: 'isolation' },
    { name: 'Machine Kickback', bodyPart: 'Glutes', category: 'isolation' },
    { name: 'Barbell Glute Bridge', bodyPart: 'Glutes', category: 'compound' },
    { name: 'Banded Glute Bridge', bodyPart: 'Glutes', category: 'compound' },
    { name: 'Single Leg Glute Bridge', bodyPart: 'Glutes', category: 'compound' },
    { name: 'Glute Cable Pull Through', bodyPart: 'Glutes', category: 'compound' },
    { name: 'Sumo Squat', bodyPart: 'Glutes', category: 'compound' },
    { name: 'Glute-Focused Step-Ups', bodyPart: 'Glutes', category: 'compound' },
    { name: 'Frog Pumps', bodyPart: 'Glutes', category: 'isolation' },
    { name: 'Donkey Kicks', bodyPart: 'Glutes', category: 'isolation' },
    { name: 'Fire Hydrants', bodyPart: 'Glutes', category: 'isolation' },
    { name: 'Abduction Machine', bodyPart: 'Glutes', category: 'isolation' },
    { name: 'Banded Walks', bodyPart: 'Glutes', category: 'isolation' },
    { name: 'Glute Romanian Deadlift', bodyPart: 'Glutes', category: 'compound' },

    // ==================== CALVES ====================
    { name: 'Machine Standing Calf Raise', bodyPart: 'Calves', category: 'isolation' },
    { name: 'Smith Machine Standing Calf Raise', bodyPart: 'Calves', category: 'isolation' },
    { name: 'Dumbbell Standing Calf Raise', bodyPart: 'Calves', category: 'isolation' },
    { name: 'Seated Calf Raise', bodyPart: 'Calves', category: 'isolation' },
    { name: 'Leg Press Calf Raise', bodyPart: 'Calves', category: 'isolation' },
    { name: 'Donkey Calf Raise', bodyPart: 'Calves', category: 'isolation' },
    { name: 'Single Leg Calf Raise', bodyPart: 'Calves', category: 'isolation' },
    { name: 'Tibialis Raise', bodyPart: 'Calves', category: 'isolation' },

    // ==================== ABS/CORE ====================
    { name: 'Standard Crunches', bodyPart: 'Abs/Core', category: 'isolation' },
    { name: 'Bicycle Crunches', bodyPart: 'Abs/Core', category: 'isolation' },
    { name: 'Reverse Crunches', bodyPart: 'Abs/Core', category: 'isolation' },
    { name: 'Cable Crunches', bodyPart: 'Abs/Core', category: 'isolation' },
    { name: 'Hanging Leg Raises', bodyPart: 'Abs/Core', category: 'isolation' },
    { name: 'Lying Leg Raises', bodyPart: 'Abs/Core', category: 'isolation' },
    { name: "Captain's Chair Leg Raises", bodyPart: 'Abs/Core', category: 'isolation' },
    { name: 'Front Plank', bodyPart: 'Abs/Core', category: 'isometric' },
    { name: 'Side Plank', bodyPart: 'Abs/Core', category: 'isometric' },
    { name: 'RKC Plank', bodyPart: 'Abs/Core', category: 'isometric' },
    { name: 'Ab Wheel Rollout', bodyPart: 'Abs/Core', category: 'isolation' },
    { name: 'Bodyweight Russian Twists', bodyPart: 'Abs/Core', category: 'isolation' },
    { name: 'Weighted Russian Twists', bodyPart: 'Abs/Core', category: 'isolation' },
    { name: 'Mountain Climbers', bodyPart: 'Abs/Core', category: 'cardio' },
    { name: 'Standard Sit-Ups', bodyPart: 'Abs/Core', category: 'isolation' },
    { name: 'Decline Sit-Ups', bodyPart: 'Abs/Core', category: 'isolation' },
    { name: 'Weighted Sit-Ups', bodyPart: 'Abs/Core', category: 'isolation' },
    { name: 'Cable Woodchops', bodyPart: 'Abs/Core', category: 'isolation' },
    { name: 'Dead Bug', bodyPart: 'Abs/Core', category: 'isolation' },
    { name: 'Bird Dog', bodyPart: 'Abs/Core', category: 'isolation' },
    { name: 'Pallof Press', bodyPart: 'Abs/Core', category: 'isolation' },
    { name: 'Dragon Flags', bodyPart: 'Abs/Core', category: 'isolation' },
    { name: 'V-Ups', bodyPart: 'Abs/Core', category: 'isolation' },
    { name: 'Toe Touches', bodyPart: 'Abs/Core', category: 'isolation' },
    { name: 'Ab Machine Crunch', bodyPart: 'Abs/Core', category: 'isolation' },
    { name: 'Flutter Kicks', bodyPart: 'Abs/Core', category: 'isolation' },
    { name: 'Scissor Kicks', bodyPart: 'Abs/Core', category: 'isolation' },
    { name: 'Copenhagen Plank', bodyPart: 'Abs/Core', category: 'isometric' },
    { name: 'Vacuum Hold', bodyPart: 'Abs/Core', category: 'isometric' },
    { name: 'Hollow Body Hold', bodyPart: 'Abs/Core', category: 'isometric' },

    // ==================== FOREARMS ====================
    { name: 'Barbell Wrist Curls', bodyPart: 'Forearms', category: 'isolation' },
    { name: 'Dumbbell Wrist Curls', bodyPart: 'Forearms', category: 'isolation' },
    { name: 'Reverse Wrist Curls', bodyPart: 'Forearms', category: 'isolation' },
    { name: "Farmer's Walks", bodyPart: 'Forearms', category: 'compound' },
    { name: 'Plate Pinch Hold', bodyPart: 'Forearms', category: 'isometric' },
    { name: 'Towel Pull-Ups', bodyPart: 'Forearms', category: 'compound' },
    { name: 'Towel Hangs', bodyPart: 'Forearms', category: 'isometric' },
    { name: 'Gripper/Grip Trainer', bodyPart: 'Forearms', category: 'isolation' },
    { name: 'Behind-the-Back Wrist Curls', bodyPart: 'Forearms', category: 'isolation' },
    { name: 'Dead Hangs', bodyPart: 'Forearms', category: 'isometric' },

    // ==================== TRAPS ====================
    { name: 'Barbell Shrugs (Traps)', bodyPart: 'Traps', category: 'isolation' },
    { name: 'Dumbbell Shrugs (Traps)', bodyPart: 'Traps', category: 'isolation' },
    { name: 'Smith Machine Shrugs', bodyPart: 'Traps', category: 'isolation' },
    { name: 'Trap Bar Shrugs', bodyPart: 'Traps', category: 'isolation' },
    { name: 'Face Pulls (Traps)', bodyPart: 'Traps', category: 'isolation' },
    { name: 'Upright Row (Traps)', bodyPart: 'Traps', category: 'compound' },
    { name: 'Overhead Carries', bodyPart: 'Traps', category: 'compound' },
    { name: 'Cable Shrugs', bodyPart: 'Traps', category: 'isolation' },
    { name: "Farmer's Walks (Traps)", bodyPart: 'Traps', category: 'compound' },

    // ==================== CARDIO ====================
    { name: 'Treadmill Walking', bodyPart: 'Cardio', category: 'cardio' },
    { name: 'Treadmill Running', bodyPart: 'Cardio', category: 'cardio' },
    { name: 'Treadmill Incline Walking', bodyPart: 'Cardio', category: 'cardio' },
    { name: 'Elliptical', bodyPart: 'Cardio', category: 'cardio' },
    { name: 'Stair Master', bodyPart: 'Cardio', category: 'cardio' },
    { name: 'Stationary Bike', bodyPart: 'Cardio', category: 'cardio' },
    { name: 'Rowing Machine', bodyPart: 'Cardio', category: 'cardio' },
    { name: 'Jump Rope', bodyPart: 'Cardio', category: 'cardio' },
    { name: 'Swimming', bodyPart: 'Cardio', category: 'cardio' },
    { name: 'Battle Ropes', bodyPart: 'Cardio', category: 'cardio' },
    { name: 'Box Jumps', bodyPart: 'Cardio', category: 'cardio' },
    { name: 'Sprints', bodyPart: 'Cardio', category: 'cardio' },
    { name: 'HIIT', bodyPart: 'Cardio', category: 'cardio' },
    { name: 'Outdoor Cycling', bodyPart: 'Cardio', category: 'cardio' },
    { name: 'Sled Push', bodyPart: 'Cardio', category: 'cardio' },
    { name: 'Sled Pull', bodyPart: 'Cardio', category: 'cardio' },

    // ==================== FULL BODY / COMPOUND ====================
    { name: 'Clean and Press', bodyPart: 'Full Body', category: 'compound' },
    { name: 'Clean and Jerk', bodyPart: 'Full Body', category: 'compound' },
    { name: 'Snatch', bodyPart: 'Full Body', category: 'compound' },
    { name: 'Thrusters', bodyPart: 'Full Body', category: 'compound' },
    { name: 'Man Makers', bodyPart: 'Full Body', category: 'compound' },
    { name: 'Turkish Get-Up', bodyPart: 'Full Body', category: 'compound' },
    { name: 'Burpees', bodyPart: 'Full Body', category: 'compound' },
    { name: 'Kettlebell Swings (Full Body)', bodyPart: 'Full Body', category: 'compound' },
]

export const bodyParts = [
    'Chest', 'Back', 'Shoulders', 'Biceps', 'Triceps', 'Forearms',
    'Quads', 'Hamstrings', 'Glutes', 'Calves', 'Abs/Core', 'Traps',
    'Cardio', 'Full Body'
]

export const splitBodyParts = [
    'Chest', 'Back', 'Shoulders', 'Biceps', 'Triceps', 'Forearms',
    'Quads', 'Hamstrings', 'Glutes', 'Calves', 'Abs/Core', 'Traps',
    'Lats', 'Full Body', 'Cardio', 'Rest Day'
]

export function getExercisesByBodyPart(bodyPart: string): ExerciseInfo[] {
    return exerciseDatabase.filter(e => e.bodyPart === bodyPart)
}

export function searchExercises(query: string, bodyPartFilter?: string): ExerciseInfo[] {
    const lower = query.toLowerCase()
    return exerciseDatabase.filter(e => {
        const matchesQuery = e.name.toLowerCase().includes(lower)
        const matchesFilter = bodyPartFilter ? e.bodyPart === bodyPartFilter : true
        return matchesQuery && matchesFilter
    })
}
